### PR TITLE
Remove quarkus extension

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by andreaTP** [comment]
@carlesarnal even just for tracking purposes, can you explain the rationale for this PR?

**Comment by carlesarnal** [comment]
The rationale is that the Quarkus extension is going to be contributed to the https://github.com/quarkiverse/quarkus-openapi-generator repo and to the Quarkiverse, so it should not be here anymore.

**Comment by andreaTP** [comment]
I think we are going a little wild here, the source code was removed > 1 month ago and is nowhere at the moment.

Probably, the best would be to revert this PR and drop the code here only when it's **merged**(if not released) from the other repo, thoughts?

cc. @EricWittmann

**Comment by carlesarnal** [comment]
> I think we are going a little wild here, the source code was removed > 1 month ago and is nowhere at the moment.
> 
> Probably, the best would be to revert this PR and drop the code here only when it's **merged**(if not released) from the other repo, thoughts?

The code "is" there (in the sense that it's in the repository, obviously not released, merged etc), but I wanted to remove the extension to not have more releases so people don't start using it from the wrong repository and dependency. If we revert this, I'm afraid people might start using it from here. In any case, open to other opinions.

> 
> cc. @EricWittmann

**Comment by carlesarnal** [comment]
FYI @andreaTP https://github.com/quarkiverse/quarkus-openapi-generator/pull/482

**Comment by andreaTP** [comment]
> FYI @andreaTP https://github.com/quarkiverse/quarkus-openapi-generator/pull/482

Thanks, I appreciate the PR is still in a Draft state.

**Pull request merged**
