### PR TITLE
Quarkus extension should generate only for a specific file

### PR DESCRIPTION
**Pull request by andreaTP**
I was having a little trouble setting up a project with the Quarkus extension, so you have 2 main changes here:

- an improvement over the IT tests of the extension, and added an additional one
- a change in the logic to avoid walking the folder and, possibly, attempting/triggering the generation on other specs files

### CODE REVIEW

**Review by MikeEdgar — APPROVED** [review]
Change looks good to me. To be clear, there is an expected behavior change (possibly breaking) where the `spec` config value must be relative to the generated output directory.

**Comment by andreaTP** [comment]
Correct, this triggers a more in depth reasoning around versioning in this project.
But it can be done outside the scope of this PR.

**Review by carlesarnal — APPROVED** [review]

**Comment by andreaTP** [comment]
@carlesarnal how do I apply those changes? Have we dropped the extension?

[Here](https://github.com/Apicurio/apicurio-codegen/pull/184) there is no information about the reasoning for removing the code nor where it's hosted.

**Comment by carlesarnal** [comment]
> @carlesarnal how do I apply those changes? Have we dropped the extension?
> 
> [Here](https://github.com/Apicurio/apicurio-codegen/pull/184) there is no information about the reasoning for removing the code nor where it's hosted.

Right, I forgot about that, I'll apply the changes to the other repo, I have a branch I'm working on to contribute the extension where I'm adding more testing etc. I'll apply these changes there.

**Comment by EricWittmann** [comment]
Can this PR be either merged or closed?

**Comment by carlesarnal** [comment]
This can be closed. We already have [plans](https://github.com/quarkiverse/quarkus-openapi-generator/pull/482), including the extension release, documentation etc to have it in the quarkus-openapi-generator repository and it will be released as soon as they get rid of their Quarkus 2 support.

**Pull request closed without merging**
