### PR TITLE
fix: display CLI option defaults

### LINKED ISSUE #127: Unintuitive definition and usage of `--code-only`
Hi,
when using the CLI I see to be unintuitive the definition and usage of `--code-only` compared to `--reactive`.
Regarding `--code-only`, I see it's enabled by default when you don't set this arg on the command line.
It means that to disable it you should use `--code-only=false` which is not clear from the help where you get:

```shell
Usage: apicurio-codegen [-hV] [--code-only] [--reactive] [--update-only]
                        [--artifact-id=<artifactId>]
                        [--generator=<generatorType>] [--group-id=<groupId>]
                        [--java-package=<javaPackage>] -o=<out> -s=<spec>
      --artifact-id=<artifactId>
                             The generated artifact id
      --code-only            Generates only the code and do not scaffold the
                               entire project

```

so it's not clear that you can assign a value to it ... would `--code-only=true|false` being better?

That's the same for `--reactive` but at least it's false by default, so it's more intuitive that adding just `--reactive` on the command line you are enabling it, when missing you are disabling it instead.

The other suggestion could be making `--code-only` false by default so having same `--reactive` behaviour.

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #127

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@ppatierno, please take a look and let me know if this resolves your concerns from #127

**Comment by ppatierno** [comment]
@MikeEdgar I have never used picocli, so was reading the doc, what does the following exactly mean?

> ALWAYS - always display the default value of this option or positional parameter, even null values, regardless what value of showDefaultValues was specified on the command

can you show me an example of the usage of `--code-only` with your change, please?

**Comment by MikeEdgar** [comment]
Before:
```
Usage: apicurio-codegen [-hV] [--code-only] [--reactive] [--update-only]
                        [--artifact-id=<artifactId>]
                        [--generator=<generatorType>] [--group-id=<groupId>]
                        [--java-package=<javaPackage>] -o=<out> -s=<spec>
      --artifact-id=<artifactId>
                             The generated artifact id
      --code-only            Generates only the code and do not scaffold the
                               entire project
      --generator=<generatorType>
                             The generator to be used
      --group-id=<groupId>   The generated group id
  -h, --help                 Show this help message and exit.
      --java-package=<javaPackage>
                             The target java package
  -o, --output=<out>         The ZIP archive to be generated
      --reactive             Generate the reactive version
  -s, --spec=<spec>          The specification to be used
      --update-only          Generates only updated files
  -V, --version              Print version information and exit.
```

Here is the after, the the `code-only` default displayed as `true`:
```
Usage: apicurio-codegen [-hV] [--code-only] [--reactive] [--update-only]
                        [--artifact-id=<artifactId>]
                        [--generator=<generatorType>] [--group-id=<groupId>]
                        [--java-package=<javaPackage>] -o=<out> -s=<spec>
      --artifact-id=<artifactId>
                             The generated artifact id
                               Default: generated-api
      --code-only            Generates only the code and do not scaffold the
                               entire project
                               Default: true
      --generator=<generatorType>
                             The generator to be used
                               Default: JAX_RS
      --group-id=<groupId>   The generated group id
                               Default: org.example.api
  -h, --help                 Show this help message and exit.
      --java-package=<javaPackage>
                             The target java package
                               Default: org.example.api
  -o, --output=<out>         The ZIP archive to be generated
      --reactive             Generate the reactive version
  -s, --spec=<spec>          The specification to be used
      --update-only          Generates only updated files
  -V, --version              Print version information and exit.
```

**Comment by MikeEdgar** [comment]
There is also an option to allow negation of `--code-only`. I'm not sure if this makes things better or worse :laughing: 

```
--[no-]code-only       Generates only the code and do not scaffold the
                         entire project
                         Default: true
```

**Review by ppatierno — APPROVED** [review]
Let's approve this way :-)

**Pull request merged**
